name: AES Encrypt & Decrypt
on: push
  # workflow_dispatch:

env:
  DEPLOYMENT_NAME: AES Encrypt & Decrypt # TODO: update to deployment name

  key: ${{ secrets.key }}

jobs:
  apigee-window-artifacts:
    name: AES Encrypt & Decrypt
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Check out Git repository code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      # Configure Workload Identity Federation and generate an access token.
      - id: 'auth'
        name: 'Authenticate to Google Apigee Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/127369686749/locations/global/workloadIdentityPools/pavan-apigee-git/providers/pavan-apigee-git'
          service_account: 'workload-identity-federation@esi-apigee-x-394004.iam.gserviceaccount.com'

      - name: AES Encrypt & Decrypt
        shell: pwsh
        run: |
          $env:TOKEN = "${{ steps.auth.outputs.access_token }}"
          $env:key = "${{ secrets.key }}"
          Invoke-Pester ./scripts.ps1 -Passthru

      - name: Remove GCP Credentials JSON File
        run: rm gha-creds*.json

      # - name: Debug Git Config
      #   run: |
      #     git config --list

      # - name: Add local files to Git local branch
      #   run: |
      #       git config --global user.email "pavan.sirasanambedu@gmail.com"
      #       git config --global user.name "pavan2esi"
      #       git add .

      # - name: Check for delta changes - Git
      #   id: check_git_changes
      #   run: |
      #     if [[ -n "$(git status --porcelain)" ]]; then
      #       echo "Local branch is not up to date with remote_branch. Pushing latest code to Git"
      #     else
      #       echo "Local branch is up to date with Remote branch."
      #       exit 0
      #     fi

      # - name: Commit files to Git
      #   run: |
      #     if [[ -n "$(git status --porcelain)" ]]; then
      #       git commit -a -m "Apigee Artifacts Export Updates"
      #       exit 0
      #     fi

      # - name: Debug Git Status
      #   run: |
      #     git status

      # - name: Push changes to Git
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.TOKEN_GIT }}
      #     branch: artifacts
          
